library ieee;
use ieee.std_logic_1164.all;

entity tb is
end entity tb;

architecture sim of tb is
  signal w_s, w_a, w_x : std_logic;
  signal in0 : std_logic;
  signal in1 : std_logic;
  signal in2 : std_logic;
  signal in3 : std_logic;
  signal in4 : std_logic;
begin
  dut: entity work.addf42_x1(rtl)
    port map (S => w_s, CO => w_a, ICO => w_x, A => in0, B => in1, C => in2, D => in3, CI => in4);
  process
  begin
    in0 <= '0'; in1 <= '0'; in2 <= '0'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '0' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDF42 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '1' report "ADDF42 mismatch" severity failure;
    report "TB_PASS addf42_x1" severity note;
    wait;
  end process;
end architecture sim;
