library ieee;
use ieee.std_logic_1164.all;

entity tb is
end entity tb;

architecture sim of tb is
  signal w_s, w_a, w_x : std_logic;
  signal in0 : std_logic;
  signal in1 : std_logic;
  signal in2 : std_logic;
  signal in3 : std_logic;
  signal in4 : std_logic;
begin
  dut: entity work.addfcscii_x1(rtl)
    port map (S => w_s, CO0 => w_a, CO1 => w_x, A => in0, B => in1, CI0 => in2, CI1 => in3, CS => in4);
  process
  begin
    in0 <= '0'; in1 <= '0'; in2 <= '0'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(0) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(1) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(2) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(3) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(4) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(5) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(6) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; in3 <= '0'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(7) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(8) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(9) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(10) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(11) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(12) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(13) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(14) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; in3 <= '1'; in4 <= '0';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(15) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(16) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(17) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(18) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(19) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(20) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(21) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(22) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; in3 <= '0'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(23) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(24) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(25) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '1' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(26) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(27) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(28) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(29) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '1' and w_a = '0' and w_x = '0' report "ADDFCSCII mismatch vec=" & integer'image(30) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; in3 <= '1'; in4 <= '1';
    wait for 1 ns;
    assert w_s = '0' and w_a = '1' and w_x = '1' report "ADDFCSCII mismatch vec=" & integer'image(31) severity failure;
    report "TB_PASS addfcscii_x1" severity note;
    wait;
  end process;
end architecture sim;
