library ieee;
use ieee.std_logic_1164.all;

entity tb is
end entity tb;

architecture sim of tb is
  signal w_o : std_logic;
  signal s : std_logic;
  signal a : std_logic;
  signal x : std_logic;
  signal m0 : std_logic;
  signal m1 : std_logic;
begin
  dut: entity work.bmuxi_x1(rtl)
    port map (S => s, A => a, X => x, M0 => m0, M1 => m1, \PP\ => w_o);
  process
  begin
    s <= '0'; a <= '0'; x <= '0'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '0'; x <= '0'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '1'; x <= '0'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '1'; x <= '0'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '0'; x <= '1'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '0'; x <= '1'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '1'; x <= '1'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '1'; x <= '1'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '0'; x <= '0'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '0'; x <= '0'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '1'; x <= '0'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '1'; x <= '0'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '0'; x <= '1'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '0'; x <= '1'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '1'; x <= '1'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '1'; x <= '1'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '0'; x <= '0'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '0'; x <= '0'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '1'; x <= '0'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '1'; x <= '0'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '0'; x <= '1'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '0'; x <= '1'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '1'; x <= '1'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '1'; x <= '1'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '0'; x <= '0'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '0'; x <= '0'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '1'; x <= '0'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '1'; x <= '0'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '0'; x <= '1'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '0'; x <= '1'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch" severity failure;
    s <= '0'; a <= '1'; x <= '1'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    s <= '1'; a <= '1'; x <= '1'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch" severity failure;
    report "TB_PASS bmuxi_x1" severity note;
    wait;
  end process;
end architecture sim;
