library ieee;
use ieee.std_logic_1164.all;

entity tb is
end entity tb;

architecture sim of tb is
  signal w_o : std_logic;
  signal s : std_logic;
  signal a : std_logic;
  signal x : std_logic;
  signal m0 : std_logic;
  signal m1 : std_logic;
begin
  dut: entity work.bmuxi_x1(rtl)
    port map (S => s, A => a, X => x, M0 => m0, M1 => m1, \PP\ => w_o);
  process
  begin
    s <= '0'; a <= '0'; x <= '0'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(0) severity failure;
    s <= '1'; a <= '0'; x <= '0'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(1) severity failure;
    s <= '0'; a <= '1'; x <= '0'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(2) severity failure;
    s <= '1'; a <= '1'; x <= '0'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(3) severity failure;
    s <= '0'; a <= '0'; x <= '1'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(4) severity failure;
    s <= '1'; a <= '0'; x <= '1'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(5) severity failure;
    s <= '0'; a <= '1'; x <= '1'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(6) severity failure;
    s <= '1'; a <= '1'; x <= '1'; m0 <= '0'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(7) severity failure;
    s <= '0'; a <= '0'; x <= '0'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(8) severity failure;
    s <= '1'; a <= '0'; x <= '0'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(9) severity failure;
    s <= '0'; a <= '1'; x <= '0'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(10) severity failure;
    s <= '1'; a <= '1'; x <= '0'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(11) severity failure;
    s <= '0'; a <= '0'; x <= '1'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(12) severity failure;
    s <= '1'; a <= '0'; x <= '1'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(13) severity failure;
    s <= '0'; a <= '1'; x <= '1'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(14) severity failure;
    s <= '1'; a <= '1'; x <= '1'; m0 <= '1'; m1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(15) severity failure;
    s <= '0'; a <= '0'; x <= '0'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(16) severity failure;
    s <= '1'; a <= '0'; x <= '0'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(17) severity failure;
    s <= '0'; a <= '1'; x <= '0'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(18) severity failure;
    s <= '1'; a <= '1'; x <= '0'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(19) severity failure;
    s <= '0'; a <= '0'; x <= '1'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(20) severity failure;
    s <= '1'; a <= '0'; x <= '1'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(21) severity failure;
    s <= '0'; a <= '1'; x <= '1'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(22) severity failure;
    s <= '1'; a <= '1'; x <= '1'; m0 <= '0'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(23) severity failure;
    s <= '0'; a <= '0'; x <= '0'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(24) severity failure;
    s <= '1'; a <= '0'; x <= '0'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(25) severity failure;
    s <= '0'; a <= '1'; x <= '0'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(26) severity failure;
    s <= '1'; a <= '1'; x <= '0'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(27) severity failure;
    s <= '0'; a <= '0'; x <= '1'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(28) severity failure;
    s <= '1'; a <= '0'; x <= '1'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "BMUXI mismatch vec=" & integer'image(29) severity failure;
    s <= '0'; a <= '1'; x <= '1'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(30) severity failure;
    s <= '1'; a <= '1'; x <= '1'; m0 <= '1'; m1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "BMUXI mismatch vec=" & integer'image(31) severity failure;
    report "TB_PASS bmuxi_x1" severity note;
    wait;
  end process;
end architecture sim;
