library ieee;
use ieee.std_logic_1164.all;

entity tb is
end entity tb;

architecture sim of tb is
  signal w_o : std_logic;
  signal in0 : std_logic;
  signal in1 : std_logic;
  signal in2 : std_logic;
  signal sel0 : std_logic;
  signal sel1 : std_logic;
begin
  dut: entity work.mux3_x1(rtl)
    port map (D0 => in0, D1 => in1, D2 => in2, S0 => sel0, S1 => sel1, \X\ => w_o);
  process
  begin
    in0 <= '0'; in1 <= '0'; in2 <= '0'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(0) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(1) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(2) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(3) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(4) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(5) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(6) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(7) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(8) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(9) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(10) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(11) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(12) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(13) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(14) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(15) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(16) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(17) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(18) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(19) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(20) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(21) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(22) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(23) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(24) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(25) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(26) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch vec=" & integer'image(27) severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(28) severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(29) severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(30) severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch vec=" & integer'image(31) severity failure;
    report "TB_PASS mux3_x1" severity note;
    wait;
  end process;
end architecture sim;
