library ieee;
use ieee.std_logic_1164.all;

entity tb is
end entity tb;

architecture sim of tb is
  signal w_o : std_logic;
  signal in0 : std_logic;
  signal in1 : std_logic;
  signal in2 : std_logic;
  signal sel0 : std_logic;
  signal sel1 : std_logic;
begin
  dut: entity work.mux3_x1(rtl)
    port map (D0 => in0, D1 => in1, D2 => in2, S0 => sel0, S1 => sel1, \X\ => w_o);
  process
  begin
    in0 <= '0'; in1 <= '0'; in2 <= '0'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; sel0 <= '0'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; sel0 <= '1'; sel1 <= '0';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; sel0 <= '0'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '0'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '0'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '0'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '0'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '0' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '0'; in2 <= '1'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '0'; in2 <= '1'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '0'; in1 <= '1'; in2 <= '1'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    in0 <= '1'; in1 <= '1'; in2 <= '1'; sel0 <= '1'; sel1 <= '1';
    wait for 1 ns;
    assert w_o = '1' report "MUX3 mismatch" severity failure;
    report "TB_PASS mux3_x1" severity note;
    wait;
  end process;
end architecture sim;
